mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from books import views
from mysite.views import hello, current_datetime, hours_ahead, homepage, meta, contact

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^meta/$', meta),
    url(r'^search/$', views.search),
    url(r'^$', homepage),
    url(r'^hello/$', hello),
    url(r'^time/$', current_datetime),
    url(r'^current_time/$', current_datetime),
    url(r'^time/plus/(\d{1,2})/$', hours_ahead),
    url(r'^contact/$', contact)
]

books/models.py
from django.db import models


class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True, verbose_name='e-mail')

    def __str__(self):
        return u'%s %s' % (self.first_name, self.last_name)


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title

mysite/forms.py
from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail addressd')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

books/views.py
from django.shortcuts import render
from django.http import HttpResponse
from books.models import Book


def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term.')
        elif len(q) > 20:
            errors.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render(request, 'search_results.html', {'books':books, 'query':q})

    return render(request, 'search_form.html', {'errors': errors})

mysite/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
import datetime
from mysite.forms import ContactForm
from django.core.mail import send_mail


def hello(request):
    return HttpResponse("Welcome to the page at %s" % request.path)


def meta(request):
    values = request.META.items()
    values = sorted(values)
    html = []
    for k, v in values:
        html.append('<tr><td>%s</td><td>%s</td></tr>' % (k, v))
    return HttpResponse('<table>%s</table>' % '\n'.join(html))


def homepage(request):
    return render(request, 'mypage.html', {'current_section': 'includes/nav', 'title': 'Home Page'})


def current_datetime(request):
    now = datetime.datetime.now()
    return render(request, 'current_time.html', {'current_date': now})


def hours_ahead(request, offset):
    try:
        offset = int(offset)
    except ValueError:
        raise Http404()
    dt = datetime.datetime.now() + datetime.timedelta(hours=offset)
    return render(request, 'hours_ahead.html', {'hour_offset': offset, 'next_time': dt})


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(cd['subject'], cd['message'],cd.get('email','noreply@example.com'),['siteowner@example.com'])
            return HttpResponseRedirect('/contact/thanks')
    else:
        form = ContactForm(initial={'subject':'I love your sizte!'})
    return render(request, 'contact_form.html', {'form':form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <h1>My helpful timestamp site</h1>
    {% block content %}{% endblock %}

    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.</p>
    {% endblock %}
</body>
</html>

templates/contact_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact us</title>
</head>
<body>
<h1> Contact us</h1>

{% if form.errors %}
    <p style="color: red;">
        Please correct the error{{ form.errors|pluralize }} below.
    </p>
{% endif %}

<form action="" method="post">
    <div class="field">
        {{ form.subject.errors }}
        <label for="id_subject">Subject:</label>
        {{ form.subject }}
    </div>
    <div class="field">
        {{ form.email.errors }}
        <label for="id_email">Your e-mail address:</label>
        {{ form.email }}
    </div>
    <div class="field">
        {{ form.message.errors }}
        <label for="id_message">Message:</label>
        {{ form.message }}
    </div>
    {% csrf_token %}
    <input type="submit" value="Submit">
</form>
</body>
</html>

templates/current_time.html
{% extends "base.html" %}

{% block title %}The current time{% endblock %}
{% block content %}
    <p>It is now {{ current_date }}.</p>
{% endblock %}

templates/hours_ahead.html
{% extends "base.html" %}

{% block title %}Future time{% endblock %}

{% block content %}
<p>
    In {{ hour_offset }} hour(s)s, it will be {{ next_time }}.
</p>
{% endblock %}

{% block footer %}
<hr>
<p>Thanks agin for visiting my site.</p>
{% endblock %}

templates/includes/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Nav</title>
</head>
<body>
<div id="nav">
    You are in: {{ current_section }}
</div>
</body>
</html>

templates/mypage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My page</title>
</head>
<body>
    <h1>{{ title }}</h1>
    {% include 'includes/nav.html' %}
</body>
</html>

templates/search_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
</head>
<body>
    {% if errors %}
        {% for error in errors %}
        <p style="color: red;">{{ error }}</p>
        {% endfor %}
    {% endif %}
    <form action="" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

templates/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Search</title>
</head>
<body>
    <p>You searched for: <strong>{{ query }}</strong></p>

    {% if books %}
        <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
        <ul>
            {% for book in books %}
                <li>{{ book.title }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No books matches your search criteria.</p>
    {% endif %}
</body>
</html>